### ISSUE TITLE
Add NCBI Logo to NCPI cloud platform main cloud image.

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#1000]
Include

![NCBI_color_f.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/b1f6cead-9b35-496c-acb1-037dc5cd9414)

in

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/2cca5bd5-a37c-47e1-a499-ec54da410648)

**Comment by linikujp** [comment]
Happy to be the 1000th submitter (original) for this issue ! :D
