### ISSUE TITLE
Update to "Data Security, Management, and Access Procedures" section

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#1008]
The NHGRI AnVIL Policy Team has developed an FAQ to make it clear how the NIH Certificates of Confidentiality Policy applies to AnVIL. Since the application of the Policy to repositories is not completely straight-forward, I’ve had this language reviewed by the NIH Office of Science Policy, as well as the Office of General Counsel. Can this please be added to the Portal? I believe it belongs in “Data Security, Management, and Access Procedures”

 

Is AnVIL covered by a Certificate of Confidentiality?  

 

Biomedical, behavioral, clinical, or other research funded wholly or in part by the NIH that collects or uses identifiable, sensitive information (including human genomic data) are automatically issued a Certificate of Confidentiality (Certificate) through a term and condition of award. Therefore, since AnVIL is NIH-funded, all data made publicly available through AnVIL via unrestricted or controlled-access are covered by a Certificate. All persons who access or work with such data managed by AnVIL must abide by the NIH Certificates of Confidentiality Policy (NOT-OD-17-109).

**Comment by NoopDog** [comment]
add to https://anvilproject.org/overview/security

**Comment by NoopDog** [comment]
This is implemented
