### ISSUE TITLE
Add "Creating a Google Cloud Account" guide to /learn Setup Billing

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#1032]
**Need**

General instructions for creating a Google  Cloud account applicable for all users who may need accounts.

**Approach**

- Markdown document in *Billing Setup* section of /learn 

**Definition of Done**

- User can find and follow instructions to create a Google Cloud account. 

- Users have information to decide if they need to create a Google Cloud account or not.

- Users are warned to check with their institutional procurement department for the preferred way to create and manage a GCP account.

- Users are informed about the $300 Google Cloud Credit program with a link to more detail.

**Comment by MillenniumFalconMechanic** [comment]
NA. See #1033.
