### ISSUE TITLE
Add Learn/Data Submitter section and document

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#1077]
https://docs.google.com/document/d/1OnBCtYdDYqwUgx0aApwCm4_vupO8uFrbCHesyNPxGPM/edit#heading=h.wuhw355xf5mk

**Comment by MillenniumFalconMechanic** [comment]
Completed.

**Comment by MillenniumFalconMechanic** [comment]
Dupe of #1079
