### ISSUE TITLE
Change the link to meeting note [NCPI improvement]

### ISSUE THREAD

**Issue by linikujp** [anvilproject/anvil-portal#1106]
"October 30th 2020 - 3rd NCPI Workshop
Agenda
Detailed Meeting Notes"

Please change the "Detailed Meeting Notes" to " Meeting Summary", and link to a shorter version: https://docs.google.com/document/d/1uqewE_hYjOVJ7jp7tz65Zvr97RazZfiB_ZcytEyf9S4/

**Comment by NoopDog** [comment]
This is now implemented.
Please see https://anvilproject.org/ncpi/progress-updates#3rd-ncpi-workshop---october-30th-2020
