### ISSUE TITLE
Clarify the path to data versus example workspaces

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#113]
The 5 example workspaces drop you into a workspace with some example data in them. They are example workflows with not so interesting data in them.

1) put a button to "Launch workspace" under here:  https://anvilproject.org/data and you get these links from here: https://anvil.terra.bio/#library/datasets

2) maybe have the datasets listed on https://anvilproject.org/ and have another page for workspaces for workflows?

3) consider having Dockstore at the bottom of the list of workflow workspaces

https://anvil.terra.bio/#workspaces/anvil-datastorage/AnVIL_CMG_Broad_Kidney_Hildebrandt_WGS/data
for GTEx v8 https://anvil.terra.bio/#workspaces/anvil-datastorage/AnVIL_GTEx_V8_hg38
for GTEx v7 https://anvil.terra.bio/#workspaces/anvil-datastorage/AnVIL_GTEx_V7_hg19

**Comment by NoopDog** [comment]
Obsolete ticket, implemented by data dash
