### ISSUE TITLE
Set up NCPI GitHub/ZenHub for tracking of use cases 

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#1136]
Use case development worksheet
https://docs.google.com/document/d/1tnoT2Y0DmPVJ7xh093j5DhJZfPxp6a8BTsjJdufqjtQ/edit

Use cases
https://docs.google.com/document/d/1y7Mt0JFA4REp2IELlWAVwiIrq_6i7_n3tQOpoxzMeWI/edit#

**Comment by MillenniumFalconMechanic** [comment]
[ZenHub board](https://app.zenhub.com/workspaces/ncpi-pm-60d41b52593813000e4af1dc/board?repos=379657842)
