### ISSUE TITLE
Add "Rolling Release Roadmap" to home page

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#116]
https://docs.google.com/presentation/d/11Uvb-H5SiNPGvLj6LpZyvZpkuLLcaM5hA3V8qE7DTEk/edit#slide=id.g41bc69e3f2_1_14

From Mo

Following up on the schematic representing the AnVIL Rolling Release Cycle, we have a draft that I am fielding feedback on. Currently the figure does a good job communicating our roadmap to the AnVIL team. I need to keep working on how to convey information to users wrt to the value of these components

**Comment by kozbo** [comment]
https://docs.google.com/presentation/d/1UFRCy-fyfBA_4QZ35dyYobLFZK-i-mwGmO7t64tz2Rw/edit?pli=1#slide=id.g6ae30168a4_2_5

**Comment by MoHeydarian** [comment]
Please work from this version of the figure: https://docs.google.com/presentation/d/1menY9-RJOvCaiYN8ol6DNdQoa5Yt96s6UhZATUTRpxw/edit?usp=sharing 

The version linked to in previous posts is linked to a few other documents and it would be good to keep it stable.

**Comment by kozbo** [comment]
@MoHeydarian We are using the last slid in the deck (the one we edited, we are rotating 90 deg. to allow for more quarter rows. We will put this on the home page. Planning to share a moch up first.

**Comment by kozbo** [comment]
Plan is to separate the data roadmap into a different chart. Go ahead and produce a graphic with the remaining elements. Note that the data roadmap might dovetail nicely with the data dashboard
