### ISSUE TITLE
Create links to workspaces with actual data

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#125]
https://anvil.terra.bio/#workspaces/anvil-datastorage/AnVIL_CMG_Broad_Kidney_Hildebrandt_WGS/data
1) put a button to "Launch workspace" under here:  https://anvilproject.org/data and you get these links from here: https://anvil.terra.bio/#library/datasets (edited) 
2) maybe have the datasets listed on https://anvilproject.org/ and have another page for workspaces for workflows?
3) consider having Dockstore at the bottom of the list of workflow workspaces
for GTEx v8 https://anvil.terra.bio/#workspaces/anvil-datastorage/AnVIL_GTEx_V8_hg38
for GTEx v7 https://anvil.terra.bio/#workspaces/anvil-datastorage/AnVIL_GTEx_V7_hg19

**Comment by NoopDog** [comment]
Highlight on home page similar to featured workspaces.

Need intro text and blurb for each data set.

**Comment by kozbo** [comment]
@MoHeydarian, wanted to run this by you.

**Comment by kozbo** [comment]
Kevin to add a link for each data set on the data page

**Comment by briandoconnor** [comment]
You can see the AnVIL workspaces a user is authorized to use with the following URL: https://app.terra.bio/#workspaces?filter=anvil_

It looks like they used a naming convention for the workspaces with project name being the next part of the name... for example, looking at CCDG:

https://app.terra.bio/#workspaces?filter=anvil_ccdg_

**Comment by kozbo** [comment]
There were concerns expressed on the Technical call that users would may be able to access the data sets once they arrived at the Terra page. It would depend on their access level. Also, each data set has at least one data access agreement that needs to be completed. How do we manage that?
Here is a query for all the AnVIL workspaces in Terra: https://app.terra.bio/#workspaces?filter=anvil_

**Comment by andrewrula** [comment]
I'm not understanding the concern. The workspaces that will show up on that page would be the workspaces that they have access to. If they don't have access, it won't show up.

Also, this is a bit of a moot point once the transition to Gen3 happens, since those buckets won't be used by users in favor of them just building a workspace through Windmill.

**Comment by NoopDog** [comment]
Nov 21 Anvil team meeting:

1) Don't wait for gen3 
2) However will just see an empty workspace list in terra and no messaging on how to gain access.
3) We could add a link to request workspace level access in dbGaP for each workspace but we need to wait for the dbGaP access guide to be developed.   

@MoHeydarian @andrewrula
