### ISSUE TITLE
Add Genome Informatics” (Nov 3-5) to upcoming events

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#1281]
The next meeting is for “Genome Informatics” (Nov 3-5): https://meetings.cshl.edu/meetings.aspx?meet=info&year=21

**Comment by mschatz** [comment]
Can we get this pushed to the portal?

**Comment by nakucher** [comment]
Ticket for this event is linked here: https://github.com/anvilproject/anvil-portal/issues/1444

**Comment by NoopDog** [comment]
Closing superseded by #1444
