### ISSUE TITLE
Add  ASHG workshops that will be held on January 19, 2022 as upcoming events

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#1282]
Then we have our ASHG workshops that will be held on January 19, 2022: https://www.ashg.org/meetings/2021meeting/attendees/schedule/ (although it is not listed on the schedule yet)

**Comment by slmosher** [comment]
Website: https://www.ashg.org/meetings/2021meeting/

-Workshop - 19JAN2022, 12:00 - 1:30 pm EST - **Structural variant discovery from long-read sequencing data on the cloud with Galaxy in Terra**
-Workshop - 26JAN2022, 12:00 - 1:30 pm EST - **Reproducible Analysis of Human Pangenome Data using the AnVIL**

**Comment by slmosher** [comment]
Dave has requested additional information, and that additional information has been drafted and will be submitted by @nakucher using the "submit an event" button on anvil project.org/events.

**Comment by mschatz** [comment]
Thanks for the update. Just wanted to make sure there was a plan in place

**Comment by NoopDog** [comment]
The related issues are here:

https://github.com/anvilproject/anvil-portal/issues/1440
https://github.com/anvilproject/anvil-portal/issues/1441

Thanks so much, @nakucher for these tickets. We will process them shortly.

Cheers,
D
