### ISSUE TITLE
Create a Logo that includes "AnVIL" text  for use where the context is not clear. 

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#134]

**Comment by MoHeydarian** [comment]
Preliminary artwork https://drive.google.com/drive/folders/18-F1s_S8FFbepbHQjOk69WV3It-IZjPk


Would be nice to include "project" in the art, to help direct people towards our project pages.

**Comment by NoopDog** [comment]
Consider using the url "Anvilproject.org" as text.
