### ISSUE TITLE
Make sure Consortia Only Workspaces from NYCG NP Alz list properly as consortia only after the next dashboard refresh

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#1386]
AnVIL_CCDG_NYGC_NP_Alz_LOAD_WGS
AnVIL_CCDG_NYGC_NP_Alz_EFIGA_WGS
AnVIL_CCDG_NYGC_NP_Alz_WHICAP_WGS

**Comment by frano-m** [comment]
Workspaces from NYCG NP Alz are consortia only with "not applicable" consent codes.
