### ISSUE TITLE
Make data submission and data access pages more prominently visible

### ISSUE THREAD

**Issue by MoHeydarian** [anvilproject/anvil-portal#143]
Feedback from @wileykl (thank you for the feedback!): the data submission and data access pages should be more prominently visible on anvilproject.org. The link to AnVIL branded Terra should also be more prominent. 

Implementing the carousel and adding cards specific to data submission, data access, and Terra could be a solution. Could we make the carousel a priority for the Portal WG, @kozbo & @NoopDog?

**Comment by kozbo** [comment]
Add "how to submit data" link and "accessing data" link on the front page above the featured workspaces.

**Comment by kozbo** [comment]
Data submission SOP is here:
https://docs.google.com/document/d/1GcBeXgQwKP82S9YZniZumhjvtv3rjm7AP_jKm7hoBac/edit?ts=5e299aa3#heading=h.lgfhww4p1l6x
