### ISSUE TITLE
Add Event - ASHG Workshop 1

### ISSUE THREAD

**Issue by nakucher** [anvilproject/anvil-portal#1440]
Thank you for submitting an event to anvilproject.org!

To expedite your event's addition to https://anvilproject.org/events,
please provide the following package information.  You can easily edit this information later by clicking "Improve this page" at the bottom of your event's detail page.

See https://anvilproject.org/guides/content/events-guide for a description of the fields listed below:

## Basics
- Event Title: Structural variant discovery from long-read sequencing data on the cloud with Galaxy in Terra
- Conference short name: ASHG 2021
- Short Description:
- Event Type: Interactive Workshop
- Date: January 19, 2022
- Time: 12:00-1:30pm
- Timezone: EST
- Location: TBD

### Event Text
In this workshop, we will guide you through an end-to-end SV identification journey using Galaxy, a platform designed to facilitate access to computational methods for researchers without a programming background. Specifically, we will use Galaxy in Terra, in the context of the NHGRI Genomic Data Science Analysis, Visualization and Informatics Lab-space (AnVIL). This cloud-based environment enables you to analyze large genomic datasets with familiar tools and reproducible workflows securely.
Through live demonstrations and interactive exercises, you will learn how to: 

1. Bring data into a project workspace in Terra
2. Combine data (your own or controlled-access) with an open-access dataset
3. Launch a Galaxy instance in Terra and run a complete workflow to identify SVs
4. Visualize results and identify potentially pathogenic variants 

The skills you will learn in this workshop will extend to other scientific use cases, datasets and tools beyond the examples shown.

### Background
Growing evidence that structural variants (SVs) are responsible for many types of diseases and traits is fueling interest in taking a fresh look at different disease types using long-read sequencing. Although short-read technologies have long been cheaper and more readily available, long-read sequencing produces data that can yield significantly more accurate results for identifying SVs. 
However, the large amounts of data and complexity of the computational methods involved can make it difficult for newcomers to access this exciting area of research, particularly in the context of the traditional computing environments that are provided by default to academic researchers. 

### Audience
Researchers and clinicians interested in exploring SV calling with long-read sequencing data. This workshop will also appeal to anyone more broadly interested in practical ways to access and analyze data in the cloud - with or without advanced computing training.

### Prerequisites (if any)
The ideal audience member will have a basic familiarity with genomics terminology and standard high-throughput sequencing data formats.

## Event Details

- Agenda:  TBD
- How to register: https://www.ashg.org/meetings/2021meeting/registration/
- Costs:  https://www.ashg.org/meetings/2021meeting/registration/
- Event home page:  TBD
- Conference website: https://www.ashg.org/meetings/2021meeting/
- Contact Info: Annual Meeting, general inquiries: meetings@ashg.org
- Hashtag: #ASHG21

**Comment by NoopDog** [comment]
Hi @nakucher also on staging. Look ok?

**Comment by nakucher** [comment]
Only comment would be to change Location TBD to Virtual. Looks good, thanks!
