### ISSUE TITLE
Add Event - ASHG Workshop 2

### ISSUE THREAD

**Issue by nakucher** [anvilproject/anvil-portal#1441]
Thank you for submitting an event to anvilproject.org!

To expedite your event's addition to https://anvilproject.org/events,
please provide the following package information.  You can easily edit this information later by clicking "Improve this page" at the bottom of your event's detail page.

See https://anvilproject.org/guides/content/events-guide for a description of the fields listed below:

## Basics
- Event Title: Reproducible Analysis of Human Pangenome Data using the AnVIL
- Conference short name: ASHG 2021
- Short Description:
- Event Type: Interactive Workshop
- Date: January 26, 2022
- Time: 12:00 - 1:30pm 
- Timezone: EST
- Location: TBD

### Event Text
This workshop will explore and demonstrate open access data from the Human Pangenome Research Consortium (HPRC), an NHGRI funded effort to create a more diverse and comprehensive reference human pangenome. We will present the data and methods produced and utilized within the first year of this project, which ultimately aims to release the assembly of high-quality diploid genomes from >350 ethnically diverse individuals across five years. Currently, raw data and assemblies from 45 individuals and associated Docker-based analysis workflows written in the Workflow Description Language (WDL) are available in the AnVIL for researchers to explore and utilize. Data and workflows will continue to be publicly released as early as possible to promote open science. These data make an excellent substrate for interaction with these data types and new workspaces and methods.

Using data and workflows from the HPRC, participants of this workshop will perform hands-on exercises including:

Registering for an AnVIL account and Google Cloud credits
Setting up a collaborative cloud workspace in Terra
Accessing and exploring hosted AnVIL data
Searching for bioinformatics workflows in Dockstore and exporting them to a Terra workspace
Configuring and launching a Docker-based WDL workflow to conduct a parallel analysis

After completing the workshop, attendees will be able to leverage AnVIL to analyze hosted datasets and launch analyses that are reproducible and scalable.

### Background
Cloud-based analysis of genomic datasets is increasingly vital for portability, reproducibility, and multi-institution collaboration, but transitioning to the cloud can be daunting. We will offer a workshop that will serve to eliminate the barriers to the adoption of these tools. Specifically, we will teach researchers how to access and utilize The Analysis, Visualization, and Informatic Lab-space (AnVIL), an environment that provides access to hosted data, reproducible tools, and collaborative workspaces, and comprehensive documentation to enable users to research in the cloud. This workshop will demonstrate how to access and explore data in AnVIL. Participants will also learn to search for analysis tools in Dockstore, a platform for sharing portable, container-based tools and workflows written in CWL, WDL, and Nextflow. Finally, they will analyze data in a Terra workspace, which is a dedicated space where researchers can access and organize the same data and tools and run analyses together.

### Audience
The intended audience for this workshop are scientists who would like to find and use tools in the cloud for genomic analysis. Researchers interested in NHGRI data are especially encouraged to attend. 

### Prerequisites (if any)
Basic knowledge of Python or R is recommended but not required.

## Event Details

- Agenda:  TBD
- How to register: https://www.ashg.org/meetings/2021meeting/registration/
- Costs:  https://www.ashg.org/meetings/2021meeting/registration/
- Event home page:  TBD
- Conference website: https://www.ashg.org/meetings/2021meeting/
- Contact Info: Annual Meeting, general inquiries: meetings@ashg.org
- Hashtag: #ASHG21

**Comment by frano-m** [comment]
Hi @nakucher - would you mind confirming for me the short name for the conference is `ASHG 2021` and hashtag `#ASHG21` (the actual conference is 2022 and I just thought I should double check)... thank you!

**Comment by frano-m** [comment]
Hi again @nakucher - would you mind also confirming the dates are correct for both ASHG workshops.

I was hunting around for more information to try and pin down the conference short name etc via the provided registration link ... and found the conferences here: https://learning.ashg.org/workshops ... the dates appear to be slightly different? Many thanks, Fran.

**Comment by nakucher** [comment]
Thanks for looking into this, Fran! The conference is ASHG 2021 and #ASHG2021 because these workshops are associated with the annual meeting in October 2021, though they're scheduled in early 2022. We got confirmation from Outreach members on the dates, but I will double check given the workshops link you found (thanks!).

**Comment by nakucher** [comment]
The dates we have are correct! The dates posted on ASHG's website (https://learning.ashg.org/workshops) were a mistake, and have since been corrected. We can go ahead and publish both workshops. Thanks!

**Comment by NoopDog** [comment]
@nakucher this is on staging. Look ok?

**Comment by nakucher** [comment]
Looks great! Only change for this and #1440 would be to change Location TBD to Virtual. Thanks!
