### ISSUE TITLE
Add Event - Genome Informatics

### ISSUE THREAD

**Issue by nakucher** [anvilproject/anvil-portal#1444]
Thank you for submitting an event to anvilproject.org!

To expedite your event's addition to https://anvilproject.org/events,
please provide the following package information.  You can easily edit this information later by clicking "Improve this page" at the bottom of your event's detail page.

See https://anvilproject.org/guides/content/events-guide for a description of the fields listed below:

## Basics
- Event Title: Genome Informatics Poster Session: Modeling the computing requirements and costs for genomics analysis in the cloud
- Conference short name: Genome Informatics
- Event Type: Poster Session
- Date: November 3-5, 2021
- Time: 1:00 - 2:00pm 
- Timezone: ET
- Location: TBD

### Event Text
The 2021 Genome Informatics Meeting will cover topics including Microbial and Metagenomics; Sequencing Algorithms, Variant Discovery and Genome Assembly; Evolution, Complex Traits and Phylogenetics; Functional Genomics; Single Cell Genomics; and Epigenetics and Genome Structure.

During the workshop poster sessions, members of the AnVIL team will present work to profile and analyze the cloud costs for many of the most widely used tools & workflows in genomics with the aim to develop a predictive model and API that can estimate the costs for running these analyses on each of the major cloud platforms.

## Event Details

- Agenda:  TBD
- How to register: https://meetings.cshl.edu/virtualregistration.aspx?meet=INFO&year=21
- Costs:  https://meetings.cshl.edu/meetings.aspx?meet=INFO&year=21
- Conference website: https://meetings.cshl.edu/meetings.aspx?meet=INFO&year=21
- Hashtag: #gi2021

**Comment by NoopDog** [comment]
Thanks, @nakucher this has been added to our work queue. We will let you know when this is on staging.

**Comment by NoopDog** [comment]
Hi, @nakucher this is on staging here:
https://staging.anvilproject.org/events/ismb2021-genome-informatics-poster-session

Can you review and let us know if any updates are required?

Cheers,
Dave

**Comment by nakucher** [comment]
Thanks for putting this together! Seeing this drawn up on the page, I think we could remove "Genome Informatics Poster Session: " from the title as well as the "Costs" heading and the associated link since the "More info" link is identical (and there isn't a way to link directly to the fees section). Otherwise, this looks good! Thanks so much!
