### ISSUE TITLE
Determine Terra link intro text, the URL and any URL parameters required.

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#15]
We will likely need some intro text for the terra link, and def will need a prod (and staging?) URL and any URL parameters.

**Comment by kozbo** [comment]
I reached out to Andrew, awaiting response.

**Comment by kozbo** [comment]
Assigning to Andrew. Note that we need a link to the AnVIL branded Terra also. Dockstore requires this link as well.

**Comment by andrewrula** [comment]
Request for text is currently out to the person who will be producing it. ETA is early next week. I'll keep you updated as things happen.
