### ISSUE TITLE
Add dbGaP Access Guide to the Portal

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#153]
Add as second level to Data Access and link to from the "External Researcher" access heading.

**Comment by MillenniumFalconMechanic** [comment]
Hi @kozbo, is there any update on this one?

**Comment by kozbo** [comment]
Not yet. I will reach out to UChicago and the Broad for how they are handling it.

**Comment by kozbo** [comment]
@NoopDog Here you go:
https://docs.google.com/document/d/1a8ms5p-nN9afuApl6DclVCvf-ol-jCja_DXHXZYu1Sw/edit
