### ISSUE TITLE
Add live data counts to home page

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#155]
@MoHeydarian can you put us in touch with the back end developer on this so we can figure out the API to call etc. 

Thanks,
D

**Comment by MoHeydarian** [comment]
Brian Walsh leads the Data Dashboard effort. His GH ID is @bwalsh, he will be at the next Portal biweekly meeting 05DEC19.

**Comment by NoopDog** [comment]
Hi @bwalsh do you have a link to any API docs (or any docs at all) that you can share with us?

Thanks!

**Comment by bwalsh** [comment]
Data dashboard now includes json output.  https://github.com/anvilproject/client-apis/blob/pyAnVIL/pyAnVIL/notebooks/figures/report-data.json

**Comment by NoopDog** [comment]
@bwalsh 

Hi Brian,

We are thinking we would like to show the total size and count of each file type on our display.
Would it be possible for you to modify the json structure for a project as follows to make this possible for us:
```
{
      "Project": 1,
      "size": "14.48 TB",
      "public": false,
      "Subject": 773,
      "Sample": 773,
      "files":[
           {
                type:"Crai"
                count:773,
                size: 744,800,000
           },
           {
                type:"Cram"
                count:773,
                size: 700,000,000
           }

       ],
      "Demographic": 773,
      "project_id": "AnVIL_CCDG_Broad_CVD_EOCAD_TaiChi_WGS",
      "source": "CCDG"
    },
```

Basically I am asking to:

1. Make a files array instead of listing them as properties on the project.
1. Make the file array elements contain the file type, file count, and total size.
1. Instead of adding the units to the file size.  can we  just always use kilobytes and we can figure out the unit to use to to display. 

Feel free to ping me on slack to discuss.
Cheers and Thanks!
Dave

**Comment by bwalsh** [comment]
Json output formatted: https://github.com/anvilproject/client-apis/blob/pyAnVIL/pyAnVIL/notebooks/figures/report-data.json


```
{
  "projects": [
    {
      "files": [
        {
          "type": "Cram",
          "size": 9857215672854,
          "count": 647
        }
      ],
      "nodes": [
        {
          "type": "Project",
          "count": 1
        },
        {
          "type": "Subject",
          "count": 647
        },
        {
          "type": "Sample",
          "count": 647
        },
        {
          "type": "Demographic",
          "count": 647
        },
        {
          "type": "Family",
          "count": 1
        }
      ],
      "size": 9857215672854,
      "public": false,
      "project_id": "AnVIL_CCDG_WashU_CVD_EOCAD_BioMe_WGS",
      "source": "CCDG"
    },
    {
      "files": [
        {
          "type": "Crai",
          "size": 984225575,
          "count": 773
        },
        {
          "type": "Cram",
          "size": 14480453123113,
          "count": 773
        }
      ],
      "nodes": [
        {
          "type": "Project",
          "count": 1
        },
        {
          "type": "Subject",
          "count": 773
        },
        {
          "type": "Sample",
          "count": 773
        },
        {
          "type": "Demographic",
          "count": 773
        }
      ],
      "size": 14481437348688,
      "public": false,
      "project_id": "AnVIL_CCDG_Broad_CVD_EOCAD_TaiChi_WGS",
      "source": "CCDG"
    },
```

**Comment by NoopDog** [comment]
Nice! Thanks.
