### ISSUE TITLE
Free Credits Overview link gives me a 404 Error

### ISSUE THREAD

**Issue by jasonwalker80** [anvilproject/anvil-portal#1589]
https://github.com/anvilproject/anvil-portal/blob/30dbd9f232e55637c5f3d154bdf9281a0f17d1a2/content/faq/resources-for-anvil-users.md?plain=1#L29

I'm not sure if the portal needs to be updated or if the Terra support page is missing/changed:
https://support.terra.bio/hc/en-us/articles/360027940952#Free%20Credits%20Overview

Either way, I get a 404 Error.

**Comment by NoopDog** [comment]
Thanks, Jason.  Will take a look.
Cheers,
D

**Comment by NoopDog** [comment]
Lets use
https://support.terra.bio/hc/en-us/articles/360046295092-Set-up-billing-with-300-Google-credits-to-explore-Terra
