### ISSUE TITLE
AGBT 2022

### ISSUE THREAD

**Issue by mschatz** [anvilproject/anvil-portal#1668]
Thank you for submitting an event to anvilproject.org!

To expedite your event's addition to https://anvilproject.org/events,
please provide the following package information.  You can easily edit this information later by clicking "Improve this page" at the bottom of your event's detail page.

See https://anvilproject.org/guides/content/events-guide for a description of the fields listed below:

## Basics
- Event Title: AGBT 2022
- Conference short name: AGBT 2022
- Short Description: Annual conference on the Advances in Genome Biology and Technology
- Event Type: Poster Presentation
- Date: Feb 28, 2022 - March 3, 2022
- Time: 
- Timezone: ET
- Location: Orlando, FL

### Event Text
See: https://docs.google.com/document/d/1MpHfs_TPC9KoNFfc0D0oTCjkKu1ndEgv9C9NweNDmC8/edit?usp=sharing

### Background
A longer form background/rationale for why this session is being provided.

### Audience
A description of the target audience/qualifications for attending.

## Event Details

- Agenda:  [Titles, dates, times, speakers, and length of sessions]
- How to register: [e.g. link to the registration website, registration open, closing dates]
- Costs:  [any fees or discount/scholarship opportunities]
- Event home page:  [on the conference website]
- Conference website: https://www.agbt.org/events/general-meeting/
- Contact Info: [Who to contact at AnVIL for more information if applicable.]
- Hashtag - #agbt21

**Comment by NoopDog** [comment]
Closing, this is on the site here
https://anvilproject.org/events/agbt2022-advances-in-genome-biology-and-technology
