### ISSUE TITLE
Add Event - AGBT

### ISSUE THREAD

**Issue by slmosher** [anvilproject/anvil-portal#1680]
Thank you for submitting an event to anvilproject.org!

To expedite your event's addition to https://anvilproject.org/events,
please provide the following package information.  You can easily edit this information later by clicking "Improve this page" at the bottom of your event's detail page.

See https://anvilproject.org/guides/content/events-guide for a description of the fields listed below:

## Basics
- Event Title: Advances in Genome Biology and Technology
- Conference short name:  AGBT 2022
- Event Type: Conference
- Date: February 28 - March 3, 2022
- Location: Bonnet Creek, Orlando, FL

### Event Text
Advances in Genome Biology and Technology (AGBT) delivers a premier experience where heads of labs, institutions, businesses, financial analysts and other high-level stakeholders come together to advance the field and drive game-changing innovation. Significant scientific advances are announced and showcased, science and industry forge enduring partnerships, and significant investments and notable acquisitions are made.

### Background
Advances in Genome Biology and Technology (AGBT) is considered the preeminent genome science and technology conference where top global researchers, leaders and innovators meet to announce new discoveries, cutting edge breakthroughs and to collaborate. As a recognized cornerstone for the genomics research community, AGBT provides an outstanding forum for exchanging information about the latest advances in DNA sequencing technologies, experimental and analytical approaches for genomic studies, and their myriad of applications. The meeting format includes daytime plenary sessions that feature invited speakers and abstract-selected talks that highlight cutting-edge research across the broad landscape of genomics. The evening concurrent session includes experimental and computational approaches for effectively utilizing the latest DNA sequencing technologies.

## Event Details

- Agenda:  https://www.agbt.org/events/general-meeting/agenda/
- How to register: https://www.nixmeetings.com/agbt2022application/registration-closed
- Event home page:  https://www.agbt.org/events/general-meeting/
- Conference website: https://www.agbt.org/
- Contact Info: https://www.agbt.org/contact/

**Comment by NoopDog** [comment]
Hi, @slmosher  this is on prod. Please use the "Improve this page"  link at the bottom of the page if we need to make any updates. Thanks! D
