### ISSUE TITLE
Add Event - ASHG 2022

### ISSUE THREAD

**Issue by slmosher** [anvilproject/anvil-portal#1681]
Thank you for submitting an event to anvilproject.org!

To expedite your event's addition to https://anvilproject.org/events,
please provide the following package information.  You can easily edit this information later by clicking "Improve this page" at the bottom of your event's detail page.

See https://anvilproject.org/guides/content/events-guide for a description of the fields listed below:

## Basics
- Event Title: American Society of Human Genetics
- Conference short name: ASHG 2022
- Short Description: The ASHG 2022 Annual Meeting provides a forum for the presentation and discussion of cutting-edge science in all areas of human genetics.
- Event Type: Conference
- Date: October 25-29, 2022
- Location: Las Angeles, CA

## Event Details

- Agenda:  TBD
- How to register: TBD
- Costs:  TBD
- Event home page:  [on the conference website]
- Conference website: https://www.ashg.org/meetings/2022-annual-meeting/
- Contact Info: Annual Meeting, general inquiries: meetings@ashg.org
- Hashtag - TBD

**Comment by NoopDog** [comment]
Hi, @slmosher  this is on prod. Please use the "Improve this page"  link at the bottom of the page if we need to make any updates. Thanks! D
