### ISSUE TITLE
Add Event - Biological Data Science 2022

### ISSUE THREAD

**Issue by slmosher** [anvilproject/anvil-portal#1682]
Thank you for submitting an event to anvilproject.org!

To expedite your event's addition to https://anvilproject.org/events,
please provide the following package information.  You can easily edit this information later by clicking "Improve this page" at the bottom of your event's detail page.

See https://anvilproject.org/guides/content/events-guide for a description of the fields listed below:

## Basics
- Event Title: Biological Data Science 2022
- Conference short name: [e.g. ISMB 2020]
- Short Description: The scope of this meeting will be the infrastructure, software, and algorithms needed to analyze large data sets in biological research.
- Event Type: Conference
- Date: November 9-12, 2022
- Location: Cold Spring Harbor, NY

### Event Text
A longer form description of the event for the event page.

### Background
A longer form background/rationale for why this session is being provided.

### Audience
A description of the target audience/qualifications for attending.

## Event Details

- Agenda:  TBD
- How to register: https://meetings.cshl.edu/meetingsregistration.aspx?meet=DATA&year=22
- Conference website: https://meetings.cshl.edu/meetings.aspx?meet=DATA&year=22
- Contact Info: TBD
- Hashtag - TBD

**Comment by NoopDog** [comment]
Hi, @slmosher  this is on prod. Please use the "Improve this page"  link at the bottom of the page if we need to make any updates. Thanks! D
