### ISSUE TITLE
Add Event - The Biology of Genomes

### ISSUE THREAD

**Issue by slmosher** [anvilproject/anvil-portal#1683]
Thank you for submitting an event to anvilproject.org!

To expedite your event's addition to https://anvilproject.org/events,
please provide the following package information.  You can easily edit this information later by clicking "Improve this page" at the bottom of your event's detail page.

See https://anvilproject.org/guides/content/events-guide for a description of the fields listed below:

## Basics
- Event Title: The Biology of Genomes
- Conference short name: BoG22
- Short Description: [max 200 char]
- Event Type: Conference
- Date: May 10-14, 2022
- Location: Cold Spring Harbor, NY

### Event Text
The 33rd annual meeting on The Biology of Genomes will begin at 7:30 pm on Tuesday, May 10, 2022 and run through lunch on Saturday, May 14. The 2022 meeting will address DNA sequence variation and its role in molecular evolution, population genetics and complex diseases, comparative genomics, large-scale studies of gene and protein expression, and genomic approaches to ecological systems. Both technologies and applications will be emphasized. There will be a special session on the ethical, legal and social implications (ELSI) of genome research as well as a session dedicated to helping trainees and early career researchers successfully navigate the NIH funding process.

## Event Details

- Agenda:  TBD
- How to register: https://meetings.cshl.edu/meetingsregistration.aspx?meet=GENOME&year=22
- Conference website: https://meetings.cshl.edu/meetings.aspx?meet=GENOME&year=22
- Hashtag - #BoG22

**Comment by NoopDog** [comment]
Hi, @slmosher  this is on prod. Please use the "Improve this page"  link at the bottom of the page if we need to make any updates. Thanks! D

**Comment by NoopDog** [comment]
Hi, @slmosher  this is on prod. Please use the "Improve this page"  link at the bottom of the page if we need to make any updates. Thanks! D
