### ISSUE TITLE
Increase visibility of AnVIL publications

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#1769]
## Need
The publications are listed in the publications section of the home page and currently in the overview/publications section. 

We want to make it more clear:

- What can be done on the platform.
- What has been done on the platform.
- How early adopters are using the platform, what tools and methods are used, and the scale and cost of analysis.

## Approach
#1767
#1768

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
