### ISSUE TITLE
Create a data high level data roadmap

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#177]
leverage Mo's chunking view of the data roadmap.
@MoHeydarian 

And combine this view with the detailed view generated by the data dash to give a fuller picture of what is coming in the longer term and what is coming short term.

**Comment by kozbo** [comment]
![Screen Shot 2020-03-03 at 3 46 55 PM](https://user-images.githubusercontent.com/17557555/75830720-5dcd3b80-5d66-11ea-98de-d6ed9fe106bc.png)

**Comment by NoopDog** [comment]
Handled by the "Consortia" page "Planned Consortia" section.
https://anvilproject.org/data/consortia#planned-consortia
