### ISSUE TITLE
Privacy Statement/GDPR

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#18]
┆Issue Number: ANG-256

**Comment by kozbo** [comment]
Assign to Ken Wiley!

**Comment by kozbo** [comment]
@wileykl Any updates? We would like to have a privacy statement so that we can gather analytics on the site

**Comment by kozbo** [comment]
Update: Work up a new TOS based on the one used for Terra. I started a doc here:
https://docs.google.com/document/d/1jt3SdC-3hk5aFgEZGTTiyGQb47as1gKwej22MLxVL5A/edit

**Comment by kozbo** [comment]
@MoHeydarian Have you reviewed this yet?

**Comment by kozbo** [comment]
Who approves the Privacy statement?
Which legal teams need to review?
repurpose the HCA statement: https://data.humancellatlas.org/privacy

**Comment by NoopDog** [comment]
Adding this here as well.

@kozbo 

So.. for our privacy page I need to know who our “Data Controllers Are”. This is a GDPR term which means:

```
The natural or legal person, public authority, agency or other body which, alone or jointly with others, determines the purposes and means of the processing of personal data.
```
Now I know who this is for Santa Cruz, and possibly the Broad as they are listed on the HCA site.

My questions are:
Are any of the below not data controllers:

Broad Institute,
Johns Hopkins University,
The University of Chicago,
Roswell Park Cancer Institute,
University of California at Santa Cruz,
Penn State University,
Washington University,
Oregon Health and Sciences University,
Harvard Medical School, Vanderbilt University,
and City University of New York.
Or is perhaps the data controller in this case NHGRI?

2) Once we determine the set of Data Controllers, I need a contact name and address for each.

I am trying to model our privacy page after this page here:
https://data.humancellatlas.org/privacy

**Comment by NoopDog** [comment]
Ok will go with the top of this:
https://docs.google.com/document/d/1Ok7LVNOvxBFOsmCu3XwjrE1mCGO9RjqQ2by64kZyrGE/edit#

@frano-m , @MillenniumFalconMechanic this is unblocked.
