### ISSUE TITLE
Add news item for Dockstore training event

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#185]
Dockstore, an introduction
https://youtu.be/1JWOVGzzgMc now on youtube 
Slide deck: https://docs.google.com/presentation/d/1j4bB_bed5dJ36U3D5HQDHIewkpm_N5T-wSUlAAXj2VA/edit#slide=id.g7a57f04dce_0_151

**Comment by NoopDog** [comment]
@MillenniumFalconMechanic @frano-m can we add the date for this to the path like

https://staging.anvilproject.org/news/2019/12/05/dockstore-training

Let's leave the JT one alone as it is already live and there may be links to it.

Let's do this for any new news when they come. 

Thanks,
D

**Comment by NoopDog** [comment]
@frano-m this is done. Was  easy to change so I changed it! Thx
