### ISSUE TITLE
Add NIH cloud platform projects informational page

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#186]
Want to communicate that the NIH has multiple cloud resources, some background to describe the NIH cloud ecosystem
Want a narrative description of each project and have a table to compliment 

Cloud platform fact sheet document
https://docs.google.com/spreadsheets/d/10gUsvjiLVf7T17I9Jo5F4dvV7gds7eA8xWyFt0ZCRw0/edit?usp=sharing

**Comment by NoopDog** [comment]
Superseded by #540
