### ISSUE TITLE
Feature AnVIL new videos in carousel

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#1951]
Need a card and text for this.

 We’d love to get one video in the carousel with a link to this page where all 9 will be added. That way it’s not so buried and people can see why AnVIL is great. It would be awesome to have this before the ECC meeting on June 2 to respond to some of their comments from the last meeting

We need text to fill two sections:

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/e64801fd-1a52-4077-898d-5ae3fb6f19c7)

1. The card title
1. The text under the card

For example, we need about this much text:

1.  A complete reference genome improves analysis of human genetic variation. (about 70 chars)

1.  Using AnVIL, researchers find the T2T-CHM13 reference genome universally improves the analysis of human genetic variation (about 125 chars)

**Comment by nakucher** [comment]
Thanks @NoopDog! Circulating this text with our content team but I have this started:

1 - Card title: How can AnVIL help my research?
2 - Description: Watch our 2-min shorts to learn how AnVIL supports reproducibility, scalability, and sharing for Data Submitters, Analysts, Lead Investigators, and Instructors.

**Comment by NoopDog** [comment]
Thanks, @nakucher we will process. Cheers, D
