### ISSUE TITLE
Use specialized TSV reader to read in tsv files

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#1952]
- Need a list of the TSV Files we read in.

**Comment by frano-m** [comment]
We read the below tsv/csv files in the following plugins:
- `plugins/utils/dashboard-source.service.js`,
- `plugins/utils/dashboard-studies-db-gap.service.js`
- `plugins/utils/dashboard-workspaces-anvil.service.js`

Files:
- `plugins/utils/dashboard-source-anvil.tsv`
-  `plugins/utils/dashboard-source-anvil.tsv` and
- `db-gap-cache/db-gap-id-accessions.csv`
