### ISSUE TITLE
A web-based analysis and collaboration tool for rare disease genomics. PMID: 35266241. 

### ISSUE THREAD

**Issue by lynnpais** [anvilproject/anvil-portal#1978]
The anvilproject.org website lists papers that cite the NHGRI Analysis Visualization
and Informatics Lab-space (AnVIL).

Pais LS, Snow H, Weisburd B, Zhang S, Baxter SM, DiTroia S, O'Heir E, England E, Chao KR, Lemire G, Osei-Owusu I, VanNoy GE, Wilson M, Nguyen K, Arachchi H, Phu W, Solomonson M, Mano S, O'Leary M, Lovgren A, Babb L, Austin-Tse CA, Rehm HL, MacArthur DG, O'Donnell-Luria A. seqr: A web-based analysis and collaboration tool for rare disease genomics. Hum Mutat. 2022 Jun;43(6):698-707. doi: 10.1002/humu.24366. Epub 2022 Mar 21. PMID: 35266241. 

Link - https://onlinelibrary.wiley.com/doi/epdf/10.1002/humu.24366

**Comment by NoopDog** [comment]
@frano-m can you add the paper above to the "AnVIL Platform, Data, Tools and Components" section on the Overview/Publications page and also add this to the homepage papers section?

https://anvilproject.org/overview/publications

**Comment by NoopDog** [comment]
@lynpais This is live!

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/a85fc6cf-7785-4636-9c3b-c5ecbcc19471)

**Comment by lynnpais** [comment]
Terrific, thank you!!
