### ISSUE TITLE
Create a NCPI specific analytics report

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#2093]
#### Need
The NCPI site is currently implemented in the same site as the AnVIL site and its analytics are currently mixed in with the AnVIL analytics in the analytics report. We would like to have a standalone NCPI report that contains only NCPI-related information.

#### Approach
Start with the AnVIL report and copy this. Changing the branding to NCPI and also filtering out the AnVIL-related content pages. That is, include only pages that start with `anvilproject.org/ncpi`. There should be a custom segment that we can define to do this filtering. Take a look and see if that is feasible.

#### Definition of Done
1. NCPI Branded report exists.
1. Only NCPI Data shows
1. Sessions that have no data/don't apply are removed.

#### Questions
1. Should this be a standalone report, or should the AnVIL report generate both? How can we create multiple reports while still maintaining code reuse?

**Comment by NoopDog** [comment]
Here’s the link on sharing the segment: https://support.google.com/analytics/answer/6121378?hl=en#share&zippy=%2Cin-this-article

**Comment by Arctenik** [comment]
With the exception of links to dbGap, none of the queries for outbound links seem to return any results

**Comment by NoopDog** [comment]
Done! Thx
