### ISSUE TITLE
Machine Learning for Health

### ISSUE THREAD

**Issue by slmosher** [anvilproject/anvil-portal#2264]
Thank you for submitting an event to anvilproject.org!

To expedite your event's addition to https://anvilproject.org/events,
please provide the following package information.  You can easily edit this information later by clicking "Improve this page" at the bottom of your event's detail page.

See https://anvilproject.org/guides/content/events-guide for a description of the fields listed below:

## Basics
- Event Title: Machine Learning for Health
- Short Description: [max 200 char] Join us on October 11, 2022 at 9:30 am ET to learn more about the [Machine Learning for Health (ML4H) workspace on Terra](https://app.terra.bio/#workspaces/uk-biobank-sek/ml4h-toolkit-for-machine-learning-on-clinical-data). This workspace contains multiple Jupyter Notebooks that show you how to perform survival analysis using the ML4H framework, do image annotation, and review and interpret model predictions.
- Event Type: [e.g. Interactive Workshop] Workshop
- Date: October 11, 2022
- Time: 9:30 am - 11:00 am
- Timezone: ET
- Location: [Physical address or virtual meeting room] Virtual

### Event Text
A longer form description of the event for the event page.
Join us on October 11, 2022 at 9:30 am ET to learn more about the [Machine Learning for Health (ML4H) workspace on Terra](https://app.terra.bio/#workspaces/uk-biobank-sek/ml4h-toolkit-for-machine-learning-on-clinical-data). This workspace contains multiple Jupyter Notebooks that show you how to perform survival analysis using the ML4H framework, do image annotation, and review and interpret model predictions.

- How to register: [e.g. link to the registration website, registration open, closing dates] https://broadinstitute.zoom.us/meeting/register/tZUude2vqz0pGtZiW5To7TkTw3GSp8qUk7vM.

**Comment by NoopDog** [comment]
Complete
