### ISSUE TITLE
Introduction to Terra

### ISSUE THREAD

**Issue by slmosher** [anvilproject/anvil-portal#2265]
Thank you for submitting an event to anvilproject.org!

To expedite your event's addition to https://anvilproject.org/events,
please provide the following package information.  You can easily edit this information later by clicking "Improve this page" at the bottom of your event's detail page.

See https://anvilproject.org/guides/content/events-guide for a description of the fields listed below:

## Basics
- Event Title: Introduction to Terra
- Conference short name: [e.g. ISMB 2020]
- Short Description: [max 200 char] For the month of October, Terra team is offering introductory Terra sessions for those who want to learn more about how to use Terra.
- Event Type: [e.g. Interactive Workshop]
- Date:
- Time:
- Timezone:
- Location: [Physical address or virtual meeting room]

### Event Text
A longer form description of the event for the event page.
Specifically, you’ll learn about:

- Terra architecture as it relates to cloud-based data sets, tools, and computing resources
- How data is organized in Terra
- How to run a WDL workflow to automate analysis
- How to launch a Cloud Environment from your Terra workspace to run interactive analysis tools like Jupyter Notebooks, RStudio, and Galaxy

## Event Details

- Agenda:  [Titles, dates, times, speakers, and length of sessions]
- How to register: [e.g. link to the registration website, registration open, closing dates] https://docs.google.com/forms/d/e/1FAIpQLSf8fJ7SljkRWeZfj2KTOJ-0Naagni5oSLFYgEUlftzU_juHrw/viewform

**Comment by NoopDog** [comment]
Done
