### ISSUE TITLE
When navigating to the top of a page the first RHS TOC element is not selected

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#229]
Expecting a little ball on "Overview" on the RHS TOC.

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/3f2eba26-2f53-4577-a7cb-311b8210bb68)

**Comment by frano-m** [comment]
@mim, think another tix has resolved this #225 and #257.

**Comment by NoopDog** [comment]
This was fixed in #225
