### ISSUE TITLE
123

### ISSUE THREAD

**Issue by Hippogriff-ui** [anvilproject/anvil-portal#2576]
Thank you for submitting an event to anvilproject.org!

To expedite your event's addition to https://anvilproject.org/events,
please provide the following package information.  You can easily edit this information later by clicking "Improve this page" at the bottom of your event's detail page.

See https://anvilproject.org/guides/content/events-guide for a description of the fields listed below:

## Basics
- Event Title:
- Conference short name: [e.g. ISMB 2020]
- Short Description: [max 200 char]
- Event Type: [e.g. Interactive Workshop]
- Date:
- Time:
- Timezone:
- Location: [Physical address or virtual meeting room]

### Event Text
A longer form description of the event for the event page.

### Background
A longer form background/rationale for why this session is being provided.

### Audience
A description of the target audience/qualifications for attending.

## Event Details

- Agenda:  [Titles, dates, times, speakers, and length of sessions]
- How to register: [e.g. link to the registration website, registration open, closing dates]
- Costs:  [any fees or discount/scholarship opportunities]
- Event home page:  [on the conference website]
- Conference website:
- Contact Info: [Who to contact at AnVIL for more information if applicable.]
- Hashtag - [The Twitter hashtag for the event]

**Comment by NoopDog** [comment]
Closing seems to be spam.
