### ISSUE TITLE
Add event: Galaxy Community Conference 2023

### ISSUE THREAD

**Issue by nakucher** [anvilproject/anvil-portal#2601]
Thank you for submitting an event to anvilproject.org!

To expedite your event's addition to https://anvilproject.org/events,
please provide the following package information.  You can easily edit this information later by clicking "Improve this page" at the bottom of your event's detail page.

See https://anvilproject.org/guides/content/events-guide for a description of the fields listed below:

## Basics
- Event Title: Galaxy Community Conference 2023
- Conference short name: GCC2023
- Short Description: The annual gathering of the Galaxy Community with opportunities to hear latest developments, get training, and meet everyone involved.
- Event Type: Conference
- Date: July 10-16, 2023
- Timezone: Australian Eastern Standard Time
- Location: Brisbane, Australia

### About GCC
The [Galaxy Community Conference (GCC)](https://galaxyproject.org/gcc) is an annual conference focused on the use and development of the [Galaxy platform](https://galaxyproject.org/) for data-intensive biomedical research.

The conference includes talks, posters, and workshops on a wide range of topics related to Galaxy, including genomics, proteomics, transcriptomics, and more. The GCC also provides an opportunity for attendees to learn about the latest developments in the Galaxy platform and to connect with other members of the Galaxy community.

### Submit an Abstract
Attending GCC is also an opportunity to share your work with the Galaxy community. You can submit an abstract to give a long talk, short talk, or present a poster about your work.
[Submit your abstract here](https://galaxyproject.org/events/gcc2023/abstracts/)!

### Audience
The conference brings together scientists, software developers, and trainers of Galaxy from a variety of disciplines to share their experiences, knowledge, and skills.

### Key Dates

Date | What
-- | --
Apr 3 | [Abstracts due for short and long talks](https://galaxyproject.org/events/gcc2023/abstracts/)
Apr 25 | Talk reviews returned
May 12 | [Early registration closes / Regular registration opens](https://galaxyproject.org/events/gcc2023/register/)
Jun 2 | [Abstracts due for posters/demos](https://galaxyproject.org/events/gcc2023/abstracts/)
Jun 12 | Poster/demo acceptance announcements
Jun 16 | [Regular registration closes / Late registration opens](https://galaxyproject.org/events/gcc2023/register/)
Jul 10 | Conference starts!
Jul 14 | CoFest starts
Jul 16 | Last day of GCC2023

## Event Details

- Agenda:  https://galaxyproject.org/events/gcc2023/schedule/
- How to register: https://galaxyproject.org/events/gcc2023/register/
- Conference website: https://galaxyproject.org/events/gcc2023/
- Contact Info: Natalie Kucher (nkucher3@jhu.edu)
- Hashtag - #gcc2023

**Comment by nakucher** [comment]
@afgane I'm looking to post about GCC on AnVIL portal! Anything you would change here?

**Comment by nakucher** [comment]
@NoopDog here's a new event we'd love to highlight on portal!

**Comment by afgane** [comment]
I think we cam omit the past dates from the `Key Dates` table and would be nice to add an explicit section for an open call for abstracts to highlight that part of the event. 

Thanks for posting this.
