### ISSUE TITLE
Add event: VADSTI 2023

### ISSUE THREAD

**Issue by nakucher** [anvilproject/anvil-portal#2602]
Thank you for submitting an event to anvilproject.org!

To expedite your event's addition to https://anvilproject.org/events,
please provide the following package information.  You can easily edit this information later by clicking "Improve this page" at the bottom of your event's detail page.

See https://anvilproject.org/guides/content/events-guide for a description of the fields listed below:

## Basics
- Event Title: AnVIL at Virtual Applied Data Science Institute 2023
- Conference short name: VADSTI
- Short Description: Tools for Applied Data Science Using Cloud-Based Platforms
- Event Type: Workshop
- Date: April 5-6, 2023
- Time: 11 am - 2 pm
- Timezone: ET
- Location: Virtual

### AnVIL Module: Tools for Applied Data Science Using Cloud-Based Platforms
AnVIL is a cloud-based platform that supports the management, analysis and sharing of biomedical data for the NHGRI research community. It aims to advance our basic understanding of the genetic basis of complex traits and accelerate discovery and development of therapies, diagnostic tests, and other technologies for diseases like cardiovascular disease or autism spectrum disorders. The platform currently hosts more than 75,000 whole human genome data sets, and offers a variety of analysis capabilities including: Terra for large scale batch computing and interactive computing; Gen3 for managing, analyzing, harmonizing, and sharing large datasets; DockStore for sharing Docker-based analysis workflows; Jupyter notebooks for organizing live code, equations, visualizations and narrative text into a single document; R Studio for interactive machine learning, statistical computing, and visualizations; Bioconductor for community-driven interactive genomics with R; and Galaxy, for accessible, reproducible, and transparent genomic science. In this module, you will be introduced to the platform, tools and functionality for data science projects.

### About VADSTI
The Howard University Research Centers in Minority Institutions, the [AIM-AHEAD program](https://aim-ahead.net/home/about/what), and the [Public Health Informatics Technology for DC (PHIT4DC) program](https://www.phit4dc.com/) is pleased to announce VADSTI 2.0, Spring 2023 Training Series to the Howard University community of researchers and beyond. The goal is to enhance data science capability and application by providing training in the foundations of programming and critical data analytic skills for planning and conducting research involving big data pertinent to minority health and health equities. The Spring Training Series is project-based and will cover topics including Foundations of Data Science, Python, Data Preparation, Exploration and Visualization, and Cloud Computing, among others.

### Background
Technological advancements and efficient use of computational tools have made it possible to generate and store large amounts of heterogeneous and complex datasets in many disciplines, including public health, clinical, biomedical, and genomics. There is therefore increased demand for data analytics capabilities to look at trends, predict outcomes, and make better clinical and health policy decisions. Skill sets in data science are particularly critical for advancing the science of minority health and health disparities. 

### Prerequisites
Register for the AnVIL module at [Eventbrite](https://www.eventbrite.com/e/virtual-applied-data-science-training-institute-vadsti-training-series-tickets-529370851467). 

No prerequisite for research knowledge topics. Basic undergraduate knowledge of algebra and probability recommended for content knowledge topics.

## Event Details

- Agenda:  Find information on the modules at the [VADSTI Spring 2023 Webpage](http://rcmi.howard.edu/vadsti23/).
- How to register: Register at [Eventbrite](https://www.eventbrite.com/e/virtual-applied-data-science-training-institute-vadsti-training-series-tickets-529370851467)
- Costs:  The event is free to attend, but registration is required.
- Event home page:  http://rcmi.howard.edu/vadsti23/
- Contact Info: Contact VADSTI (vadsti@howard.edu) with any questions.

**Comment by nakucher** [comment]
@NoopDog Hey Dave, here's another upcoming event we'd love to put on the portal!

**Comment by frano-m** [comment]
Hi @nakucher - would you mind confirming the times for this event `11 am - 2 pm` relate to both days `April 5-6, 2023`? I am unable to view the http://rcmi.howard.edu/vadsti23/ page for some reason. Thank you!
