### ISSUE TITLE
[AnVIL Next] Create CSER research materials page

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [anvilproject/anvil-portal#2684]
#### Approach
* See [existing content](https://cser-consortium.org/cser-research-materials).
* See [mocks for resources](https://www.figma.com/proto/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=2530-28997&scaling=min-zoom&page-id=2529%3A26617&starting-point-node-id=2529%3A26618&hide-ui=1).
* TBD - JSON of content to be provided.
* Downloaded resources will be hosted as static files; see https://github.com/anvilproject/anvil-portal/issues/2683.

**Comment by frano-m** [comment]
### Approach

- CSER Phase 2 Validation Templates is out of scope of this ticket.

**Comment by NoopDog** [comment]
Complete
