### ISSUE TITLE
[AnVIL Portal] Terms of Service

### ISSUE THREAD

**Issue by frano-m** [anvilproject/anvil-portal#2697]
#### Approach
Start with a stub:
- [x] Path: anvil-explorer-tos
- [x] Title: AnVIL Explorer Terms of Service
- [ ] Content: TBD **Waiting for content to be finalized by UCSC legal.**

**Comment by MillenniumFalconMechanic** [comment]
Waiting for content.

**Comment by MillenniumFalconMechanic** [comment]
Duplicate of https://app.zenhub.com/workspaces/team-boardwalk-5d680d7e3eeb5f1bbdf5668f/issues/gh/databiosphere/data-browser/3684.
