### ISSUE TITLE
[AnVIL Next] Validate that the Next/CSER pages are showing up in the dev and prod GA4 accounts

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#2769]
Go to:

https://anvilproject.org/consortia
https://anvilproject.org/consortia/cser

And validate that the dev and prod versions of these pages:

1. Visiting
2. Scrolling
3. Selecting links

Registers properly in the corresponding GA4 sites.

**Comment by hunterckx** [comment]
Prod looks good, dev doesn't seem to be working

**Comment by NoopDog** [comment]
complete
