### ISSUE TITLE
Add a news item for  the ALS Compute Release

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#2826]
From @slmosher 

> I’d like to post a blogpost in https://anvilproject.org/news to go along with the ALS Compute release. Here is a link to a doc w/ text to be used for the post: https://docs.google.com/document/d/1p2SM_a9oESfIkx2SsFN30i9Y9vwy5oSMRZi0K8qRxoc/edit?usp=sharing.

**Comment by jpaten** [comment]
Hi @slmosher @NoopDog! Sorry for the delay in getting to this, I can definitely do that. Is there a particular date you want it to be associated with? I can just do today if it doesn't matter, but just wanted to check first!

**Comment by slmosher** [comment]
The data are already released, lets post this ASAP! Thanks @jpaten !

**Comment by jpaten** [comment]
Great thanks! Just submitted it as a PR!
