### ISSUE TITLE
Add event Festival of Genomics and Biodata 2023

### ISSUE THREAD

**Issue by nakucher** [anvilproject/anvil-portal#2856]
Thank you for submitting an event to anvilproject.org!

To expedite your event's addition to https://anvilproject.org/events,
please provide the following package information.  You can easily edit this information later by clicking "Improve this page" at the bottom of your event's detail page.

See https://anvilproject.org/guides/content/events-guide for a description of the fields listed below:

## Basics
- Event Title: Festival of Genomics and Biodata
- Conference short name: AnVIL 2023
- Short Description: The world's largest Genomics and Biodata event
- Event Type: Conference
- Date: October 5-6, 2023
- Time: 11:40 AM - 12:10 PM
- Timezone: ET
- Location: Boston, MA, USA

### Event Text

Connect with the AnVIL Team at the Festival of Genomics and Biodata in Boston, MA!

Hear how the NHGRI Genomic Data Science Analysis, Visualization, and Informatics Lab-Space (AnVIL) (https://anvilproject.org/), is a secure cloud-based platform for genomics and biomedical research. AnVIL currently provides harmonized access to more than 600,000 genomes from several key NHGRI projects along with thousands of analysis tools and workflows. This presentation will introduce the data and analysis capability of AnVIL and discuss the future of biomedical data analysis, sharing, and interoperability.

![Mosher](https://github.com/anvilproject/anvil-portal/assets/80000074/9aaa2e4c-fb43-444c-bcfc-6a37a4c10a34)

### Background

Whether you’re pushing the frontiers of scientific knowledge, supporting patients in a clinical setting, or working in drug discovery & development, here’s one event in 2023 that you can’t afford to miss.

From deciphering data to cracking cancer, the Festival is brimming with essential insights from world-class speakers, challenging discussions on emerging topics, and powerful learning and networking experiences. Not only that – it’s free for most attendees.

Registering will give you access to 7 theaters packed full of incredible speakers, as well as networking and access to a variety of unique features that will help you push your work forwards and have fun at the same time.

### Prerequisites

Register for the conference at the conference webpage: https://festivalofgenomics.com/boston/en/page/registration.

## Event Details

- Agenda: Attend the AnVIL talk at the Biodata Stage on October 4, 2023 at 11:40 AM to 12:10 PM: https://connect.frontlinegenomics.com/widget/event/festival-of-genomics-and-biodata-boston/planning/UGxhbm5pbmdfMTI2NTY2Nw==.
- How to register: https://festivalofgenomics.com/boston/en/page/registration
- Event home page: 
- Contact Info: Contact [Stephen Mosher](stephen.mosher@jhu.edu) with any questions.

**Comment by jpaten** [comment]
Hi! Just wanted to check before I add the event, should the date listed be the dates of the conference, or just the AnVIl talk on October 4?

**Comment by nakucher** [comment]
Hi @jpaten, the conference dates would be great!

**Comment by jpaten** [comment]
Great, thanks! Will submit today
