### ISSUE TITLE
[AnVIL Next] Add Overview content to next

### ISSUE THREAD

**Issue by frano-m** [anvilproject/anvil-portal#2895]
Move the following content from https://anvilproject.org/overview to Next:

- What is AnVIL? (https://anvilproject.org/overview)
- Platform and Data Security (https://anvilproject.org/overview/security)
- Supported by NHGRI (https://anvilproject.org/overview/project-sponsor)
- ~Publications~
- Citing AnVIL (https://anvilproject.org/overview/cite-anvil)

Ignore publications for now.
Do not update the header links, we will do this later.
Refer to [mocks](https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL?type=design&node-id=6148-18913) for reference.

**Comment by frano-m** [comment]
Enable the `/overview` page to download the poster.

1. Update [figure component caption prop](https://github.com/anvilproject/anvil-portal/blob/43e139648caac15546f08bb8197f86f2a1b8e94d/next/components/common/Figure/figure.tsx#L8) from a `string` to `ReactNode`. You will need to import `ReactNode` from React, in the import section of the component. e.g. `import { ReactNode } from "react";`.

```
export interface ImageProps extends StaticImageProps {
  caption?: ReactNode;
}
```

2.  Copy the poster [from](https://github.com/anvilproject/anvil-portal/blob/9bfd677831523d23141620d23238cecc561608c6/content/overview/_files/2020.09.21.T2T.HRPC.AnVIL-Poster-wide.pdf) to: `next/public/consortia/overview/files/2020.09.21.T2T.HRPC.AnVIL-Poster-wide.pdf`. Notice the `_files` directory is now named `files`.

3. Update the figure in `overview.mdx` [here](https://github.com/anvilproject/anvil-portal/blob/f666b0420cbff6e4f7495ba43c22aeb68a518a59/next/docs/overview.mdx).

```
<Figure
  alt="Overview of AnVIL"
  caption={
    <>
      From the NHGRI Genomic Data Science Analysis, Visualization and
      Informatics Lab-space (AnVIL) poster presented at{" "}
      <Link label="#T2THPRC" url="https://twitter.com/hashtag/T2THPRC" />. (
      <a
        href="/consortia/overview/files/2020.09.21.T2T.HRPC.AnVIL-Poster-wide.pdf"
        download
      >
        Download the Poster
      </a>
      )
    </>
  }
  src="/consortia/overview/images/overview.png"
/>
```

**Comment by MillenniumFalconMechanic** [comment]
Completed.
