### ISSUE TITLE
Add FAQ link in a more prominent location

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#293]
Our NHGRI program officer asked: 
"I wonder if the FAQs should also be available as another link in the menu at the top right of the home page"
I suggested the bottom of the page next to the "Help" link, awaiting a reply

**Comment by NoopDog** [comment]
Lets combine help and faq in to a single tab called faq.
Add faq to the top nav after events and before contact and link to faq.
Help in footer links to help section faq tab.
