### ISSUE TITLE
Replace references to Gen3 with AnVIL Data Explorer

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#3061]
### Need
Gen3 is no longer the data repository for the AnVIL project. The AnVIL Data Explorer has replaced Gen3.
We need to find each text reference to Gen3 and update or remove it appropriately. 

1. Find the remaining references and list them in a spreadsheet. (Search the code/docs folders for Gen3)
2. Schedule a call to review each usage and see if it can be deleted or if it needs to be re-written.

**Comment by jpaten** [comment]
Hi @NoopDog! See the proposed changes below. Most of them were made by @esthermcdade, but I added a couple that I didn't see on her sheet!

#### Notices needed
- [ashg2020-data-in-the-cloud.mdx](https://anvilproject.org/events/ashg2020-data-in-the-cloud)
  - [ ] Approved
  - [ ] Implemented
- [ashg2020-gwas-analysis-with-galaxy.mdx](https://anvilproject.org/events/ashg2020-gwas-analysis-with-galaxy)
  - [ ] Approved
  - [ ] Implemented
- [ismb2020-finding-and-analyzing-data-in-the-cloud.mdx](https://anvilproject.org/events/ismb2020-finding-and-analyzing-data-in-the-cloud)
  - [ ] Approved
  - [ ] Implemented 
- [vadsti2021.mdx](https://anvilproject.org/events/vadsti2021)
  - [ ] Approved
  - [ ] Implemented
- [vadsti2023.mdx](https://anvilproject.org/events/vadsti2023)
  - [ ] Approved
  - [ ] Implemented
- [announcing-gen3-availability-in-anvil.mdx](https://anvilproject.org/news/2020/06/19/announcing-gen3-availability-in-anvil)
  - [ ] Approved
  - [ ] Implemented

This one I'm not sure about, maybe it would make sense to create smaller warnings associated with each workshop that mentioned Gen3?
- [ ] [workshop-archive.mdx](https://anvilproject.org/learn/workshop-archive)
  - Lists various workshops, some of which involve Gen3.
  - [ ] Approved
  - [ ] Implemented
 
#### Changes needed
The following items need changes, which are documented in [this spreadsheet](https://docs.google.com/spreadsheets/d/1X1orCrvPWUk1Wh3e0I92ekZsBYQUG2-0RA04hNOwunc/edit?gid=0#gid=0)
- [team.mdx](https://anvilproject.org/team
  - [x] Approved (#3292)
  - [x] Implemented (#3293)
- [news-item-guide.mdx](https://anvilproject.org/guides/content/news-item-guide)
  - [ ] Approved
  - [ ] Implemented
- [data-access-controls.mdx](https://anvilproject.org/learn/accessing-data/data-access-controls)
  - [ ] Approved
  - [ ] Implemented
- [requesting-data-access.mdx](https://anvilproject.org/learn/accessing-data/requesting-data-access)
  - [ ] Approved
  - [ ] Implemented
- [overview-of-account-setup.mdx](https://anvilproject.org/learn/account-setup/overview-of-account-setup)
  - [ ] Approved
  - [ ] Implemented
- [setting-up-lab-accounts.mdx](https://anvilproject.org/learn/investigators/setting-up-lab-accounts)
  - [ ] Approved
  - [ ] Implemented
- [security.mdx](https://anvilproject.org/overview/security)
  - [ ] Approved
  - [ ] Implemented

**Comment by jpaten** [comment]
Text for new warnings:

Starting October 1, 2024, AnVIL Gen3 will be decommissioned. Please see [Sunsetting Gen3 Functionality in AnVIL](https://anvilproject.org/news/2024/09/16/sunsetting-gen3-in-anvil) for more information.

**Comment by MillenniumFalconMechanic** [comment]
Completed.
