### ISSUE TITLE
Add ASHG event

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#308]

**Comment by kozbo** [comment]
Title: GWAS analysis with Galaxy on the Analysis Visualization Integrated Lab-space (AnVIL)

Date: Wednesday, October 28, 2020

Session Start Time: 7:15 a.m.

Session End Time: 8:45 a.m.

Location: San Diego Convention Center, 111 West Harbor Drive, San Diego, CA 92101

Description:

Genome wide association studies (GWAS) require processing and analysis of thousands of samples, generally requiring complex computational pipelines that require an understanding of multiple programming languages, access to computational resources, and a secure environment to work with protected human data. Many researchers do not have the expertise and access to resources for complex genomic analysis, like GWAS. The Analysis, Visualization, and Integrative Lab-space (AnVIL) is a cloud based environment that serves to provide access to high-value human genomic data sets and access to commonly used bioinformatic tools and workflows all in a secure environment. Galaxy is an interactive analysis platform that provides access to commonly used bioinformatic tools through a graphical user interface and is available on AnVIL. This interactive workshop will introduce the AnVIL ecosystem and its components, highlighting Gen3 for data exploration, Dockstore as the workflow repository, and Terra for launching, scaling, and sharing interactive analysis environments. Attendees will use AnVIL to launch Galaxy and create, modify, and execute a Galaxy Workflow for GWAS analysis to demonstrate batch processing in Galaxy. Attendees will visualize identified variants in interactive visualizations and learn how to share their Galaxy Workflows on AnVIL. Workshop participants will gain an understanding of how to use cloud computing with AnVIL to perform reproducible, transparent, and accessible genomic analysis.

 

Intended Audience:

The target audience for this workshop are scientists wanting to do GWAS analyses but with limited informatics expertise and support. The AnVIL ecosystem provides a pre-configured environment in which to conduct human genomics research and Galaxy is one of many tools available for bench-biologists to use for reproducible data analysis.

**Comment by NoopDog** [comment]
@MoHeydarian Re opening this one too - can we get the link to this on the conference website and a link to register for the event? Thanks!

**Comment by NoopDog** [comment]
Will make the reg link a separate issue.
