### ISSUE TITLE
[AnVIL Portal] Update links for the updated mocks

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#3136]
#### Need
Feedback that the links do not stand out in the backpages.

#### Approach
Add an underline and color change.

[Figma](https://www.figma.com/design/JOUDXkKfgivRNFdBsWDPEH/AnVIL?node-id=6698-12851&node-type=canvas&t=AeHFOvyHFTrmDZcU-0)

<img width="491" alt="image" src="https://github.com/user-attachments/assets/3b735fda-f3ca-4ca9-b046-58659e9536b9">

**Comment by frano-m** [comment]
Site matches [mocks](https://www.figma.com/design/wxBBIrZcZb6IhYSg4d8B7J/BRC-Analytics-Homepage?node-id=223-188&m=dev).

**Comment by NoopDog** [comment]
Hi @frano-m reopening this one. I am expecting the links to be underlined as in 

https://www.figma.com/design/JOUDXkKfgivRNFdBsWDPEH/AnVIL?node-id=6698-14644&node-type=frame&t=GBiAo7PoKckZtNS3-0

<img width="786" alt="image" src="https://github.com/user-attachments/assets/c65fbf67-e06a-4cb2-a174-e010145e5c50">

Instead, we currently have like:

<img width="812" alt="image" src="https://github.com/user-attachments/assets/146bfe6c-1536-403f-8c39-ae91f4fe1098">

**Comment by NoopDog** [comment]
Let's make this the standard back page link style everywhere. Is there a Findable ticket that needs to be opened for this? @frano-m

**Comment by frano-m** [comment]
Closing; fixed by https://github.com/anvilproject/anvil-portal/pull/3331.

**Comment by NoopDog** [comment]
Hi @frano-m can we leave this open till #3331 is merged and we validate the fix?

**Comment by frano-m** [comment]
Reopening until #3331 is merged, and fix is validated.

**Comment by NoopDog** [comment]
Complete

<img width="964" alt="image" src="https://github.com/user-attachments/assets/3cfab67f-0d2b-46fe-aebf-d5f392600c6c">

Thanks @frano-m
