### ISSUE TITLE
Add warning box indicating GTEx v8 Free Egress program is sunsetting

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#3140]
Content Needed:

1. When is it being sunset?
2. How will the user access GTEX V8 free or otherwise after this?

**Comment by kbalacon** [comment]
**Proposed text:** Starting October 1, 2024, the AnVIL Gen3 Commons and free downloadable version of GTEx v8 through Gen3 will be decommissioned. See full announcement here. [add link to announcement]

**Comment by NoopDog** [comment]
Complete
