### ISSUE TITLE
Document GA's built-in outbound links event

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [anvilproject/anvil-portal#3203]
#### Need
We would like to use outbound link usage information to drive homepage layout.

#### Approach
Document GA's built-in outbound links (e.g. limitations, included parameters).

**Comment by jpaten** [comment]
GA4 includes outbound link tracking as part of the Enhanced Measurement feature, which is already enabled for all of our sites. This creates dimensions for the url, the site domain, and the text the user clicked on to access that link. We don't need to do anything else to enable this, the data is already being collected. See below an example query from the GA4 Query Explorer. I'll send the results in Slack!

![Image](https://github.com/user-attachments/assets/071f974e-f01f-4cdc-aa5a-497f479d197c)
