### ISSUE TITLE
[AnVIL Portal] Update GTM outbound link configuration 

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [anvilproject/anvil-portal#3232]
#### Need
Outbound links should track the source URL and capture the fragment if any.

#### Definition of Done
Additional outbound link information is accessible in the query manager for prod and staging:
- [x] anvilproject.org - GA4
- [x] anvilproject.dev.clevercanary.com - GA4

**Comment by jpaten** [comment]
Working on prod and staging @MillenniumFalconMechanic 

Prod:
![Image](https://github.com/user-attachments/assets/3f1e1014-4d91-4392-8870-9192458f0ef2)


Staging:
![Image](https://github.com/user-attachments/assets/6c7b418f-f464-44af-9b73-d7743cd8b632)

**Comment by MillenniumFalconMechanic** [comment]
Thanks Jonah!
