### ISSUE TITLE
AnVIL Champions page

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#3283]
#### Need
https://docs.google.com/document/d/10TrH4styn1LNFoVewKU4-ykRinMNRVBDsUbDftH5MN8/edit?tab=t.0

#### Approach
* Add an  "AnVIL Champions" menu item at the top level in the "More" nav option between "Team" and "FAQ".
* See [document](https://docs.google.com/document/d/10TrH4styn1LNFoVewKU4-ykRinMNRVBDsUbDftH5MN8/edit?tab=t.0) for actual content.
* See [design ticket](https://github.com/clevercanary/cc-design/issues/191) and [mocks](https://www.figma.com/design/JOUDXkKfgivRNFdBsWDPEH/AnVIL?t=vei1lw9zqxdXC1xS-0):

<img width="930" alt="image" src="https://github.com/user-attachments/assets/15507217-b537-455d-b015-54eb66390167">

**Comment by KatherineCox** [comment]
Video is up at https://youtu.be/PptqHHXke54 (I've also updated the Google Doc with this link)

For the images, we're forming a new cohort of AnVIL Champions that should be starting up in the next month or so, and we're still working with some of the communities to finalize who the Champions will be (some have been confirmed, some still waiting). We'd like to try to get the page up soon, and then we can submit a PR to update it once we've got the rest of the Champions finalized.

In the meantime, could we get the page up either with a placeholder image or no image for the two people currently listed in the Google Doc?  (A placeholder image may be necessary at some point anyway, if we're not able to get pictures from all the Champions).

We've got a little bit of a chicken-and-egg thing going here - it's easier to get the Champions to send us an image if they can see the page, and of course it's easier for you to make the page once you've got the images... so we're trying to push forward on both sides and we'll update with the images as they come in.
