### ISSUE TITLE
Update hero unit text to communicate value prop

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#33]
- Replace 'Welcome to AnVIL" and possibly the 2nd sentence.

┆Issue Number: ANG-252

**Comment by kozbo** [comment]
How about "AnVIL: Analysis, Visualization and Informatics Lab-space" instead of "Welcome to AnVIL"?
NHGRI link:https://www.genome.gov/Funded-Programs-Projects/Computational-Genomics-and-Data-Science-Program/Genomic-Analysis-Visualization-Informatics-Lab-space-AnVIL
