### ISSUE TITLE
data dashboard link position

### ISSUE THREAD

**Issue by vjcitn** [anvilproject/anvil-portal#333]
on left sidebar data dashboard is at bottom.  i think separating it from the data link in the sidebar is a little confusing ... i got lost because i do not view the sidebar as the fundamental control, so it may be my problem.  but a) i think dashboard should have higher position on the sidebar, and b) i would propose that the data/data dashboard distinction be eliminated if possible.  the narrative about studies can flow smoothly with the table.

**Comment by NoopDog** [comment]
Thanks, will give this a shot and see how this looks.

**Comment by NoopDog** [comment]
@frano-m I@MillenniumFalconMechanic I tried this but the right nav runs down into the table. Let's discuss how we can do this. Thanks!
