### ISSUE TITLE
Update GTEx egress instructions

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [anvilproject/anvil-portal#3343]
#### Definition of Done
* Remove all text after the warning box on the [GTEx v8 - Egress Instructions](https://anvilproject.org/learn/reference/gtex-v8-free-egress-instructions) page.

**Comment by jpaten** [comment]
Hi @MillenniumFalconMechanic! Just one quick question - do you want me to delete the image files associated with this page, or should we leave them in for archival reasons? I also noticed a couple of the images in the same folder (`public/consortia/learn/reference/`) aren't referenced anywhere, are those safe to delete?

**Comment by NoopDog** [comment]
Delete! Thx

**Comment by jpaten** [comment]
Remove link on the sidebar as well
