### ISSUE TITLE
Re-Run the outbound links analytics script

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#3374]
Now that we have had the outbound links collecting for a while. Run the report for the last 30 days and lets review the spreadsheet together.

**Comment by jpaten** [comment]
Track both external and internal links, and add a column to the report that marks whether a link is internal or external. Need:
- Internal / External
- Current Page
- Clicked Page
- \# Total clicks
- \# Unique users clicking the link

**Comment by jpaten** [comment]
@NoopDog I've pushed the changes to the script to generate the sheet you specified to the old #3202 branch, the PR is [here](https://github.com/anvilproject/anvil-portal/pull/3217).
