### ISSUE TITLE
Minor corrections to Privacy statement

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#393]
This from
Ghanaim, Elena (NIH/NHGRI) [E]

Hi Kevin,

Thanks for reaching out! I noticed one typo and had one other overarching thought. However, I am no expert on website privacy statements, so feel free to ignore!

In the following sentence, does the word “Web” need to be capitalized? It seems inconsistent with other sentences. “This information is used to improve Web presentation and utilization.”
Would it be useful to distinguish this privacy statement from the privacy statement on anvil.terra.bio (https://anvil.terra.bio/#privacy)? Perhaps it is useful not to mention the AnVIL platform, however, some might confuse the two and wonder why there isn’t a mention about genomic and biomedical research data privacy. Again, feel free to ignore this idea!

Hope this is helpful input.

Sincerely,

Elena

**Comment by NoopDog** [comment]
Cap W is fixed. 

Let's add to the "External Sites" section Privacy links for Dockstore and AnVIL terra for now and add Gen3 when it comes online.
