### ISSUE TITLE
Fix link for "Anatomy of a Workspace" in guides section

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#414]
https://anvilproject.org/training/guides#terra-workspaces

This link gives a 404
https://support.terra.bio/hc/en-us/articles/360022716811-The-Workspace-Organize-data-organize-and-run-analysis-tools

@MoHeydarian do you know what the correct link is?

**Comment by MillenniumFalconMechanic** [comment]
Completed.
