### ISSUE TITLE
Create helpdesk email list/contact

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#42]
@MoHeydarian can you take this one?

┆Issue Number: ANG-247

**Comment by NoopDog** [comment]
Have a help page with  a description and help link for each tool used in AnVIL so the user can decide what is the appropriate community to send their request to.

**Comment by NoopDog** [comment]
add to help page when this is done.

**Comment by NoopDog** [comment]
Hi @MoHeydarian any luck in getting this help@anvilproject.org email setup? Checking if you are the right person to do this. (not sure who owns the domain and controls the dns/mx etc.)

If there is a long lead time for this, maybe we put an existing individual or group email there has a placeholder while we work this out?

**Comment by MoHeydarian** [comment]
Hi @NoopDog, Nate can set up the email list once he returns from vacation. In the meantime we can use the AnVIL PM list for contact/help. Will share offline.

**Comment by kozbo** [comment]
use  anvil-project-managers@lists.anvilproject.org for now
