### ISSUE TITLE
Add "Data" top level section

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#44]
Highlight 

GTEx
eMerge
CMG
CCDG
1000 Genomes

Get text for each one from the data access working group

┆Issue Number: ANG-246

**Comment by kozbo** [comment]
from https://ucsc-cgl.atlassian.net/browse/ANG-140

Data Access Working Group
Co-Chairs: Carolyn Hutter (NHGRI), Stacey Donnelly (Broad)
Members: Jonathan Lawson (Broad), Elena Ghanaim (NHGRI), Andrew Rula (Broad), Rich Silva (Broad), Garrett Rupp (UChicago)
