### ISSUE TITLE
Add Tools section 

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#45]
Could be top level or home page or both

List the tools and get text on each on how they interact with anvil

Bioconductor
Galaxy
Docstore
Terra 
Gen3/Windmill

┆Issue Number: ANG-245

**Comment by kozbo** [comment]
Biconductor: Wikipedia - Bioconductor is a free, open source and open development software project for the analysis and comprehension of genomic data generated by wet lab experiments in molecular biology. Bioconductor is based primarily on the statistical R programming language, but does contain contributions in other programming languages.
