### ISSUE TITLE
Basic Data Flow "Cartoon" for Platform Page

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#474]
Similar to
![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/4b9f7691-b98b-49bc-8827-34ba23fec57c)

**Comment by kozbo** [comment]
Here is the basic flow (no frills) 
https://docs.google.com/presentation/d/1WPJVC4kPYLHJVz1O_aWxQz1xrSl29ACJ03IOSiCU_QI/edit?usp=sharing
