### ISSUE TITLE
Update release roadmap

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#486]

**Comment by NoopDog** [comment]
@kozbo who can help us update this? Will need some 2021 items. 

![image](https://user-images.githubusercontent.com/3239697/101731115-f9b37280-3a6f-11eb-80f7-261cc52c6e8e.png)

**Comment by kozbo** [comment]
First, please remove the current roadmap. It looks bad to have old data on the site.

**Comment by kozbo** [comment]
seqr and UCSC Genome Browser

**Comment by kozbo** [comment]
Obsolete for now, add new issue when we have more specifics
