### ISSUE TITLE
Update working groups section with latest info

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#49]
https://docs.google.com/document/d/1PsZc0BdaAZ9ddI2o1cv8CYfmIJqb0eVbAMBUHhW7g1Q/edit

- [x] Add the additional working groups
- [x] Check if any members need to be updated
- [x] Update text to use "Co-Chairs"
- [x] Add text from "Description (for website)" section of the above doc to each working group.
- [x]  Remove "Current" from working groups title and use just "Working Groups"

**Comment by frano-m** [comment]
PR[content] https://github.com/anvilproject/anvil-portal-content/pull/9
