### ISSUE TITLE
Announce ASHG training event on site

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#50]
┆Issue Number: ANG-241

**Comment by kozbo** [comment]
October 15-19
http://www.ashg.org/2019meeting/asp/soe/webroot/soe.shtml#?search=terra
http://www.ashg.org/2019meeting/asp/soe/webroot/soe.shtml#?search=galaxy

**Comment by NoopDog** [comment]
add as a past event. See if we can get slides etc.

**Comment by kozbo** [comment]
This now goes into past events

**Comment by kozbo** [comment]
This information is already in Events, closing
