### ISSUE TITLE
Possible Training sitemap updates

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#534]
Getting Started
"Library"
Contact

**Comment by kozbo** [comment]
Planning a 3 tier approach:

1. What is AnVIL, how to find out if AnVIL data is of interest to you, how to gain access
2. What are the components of AnVIL, high-level getting started on each component
3. Detailed information on each tool or component (this information is not on the main portal site)

Note that use-case scenario structured training will also be provided
