### ISSUE TITLE
NCPI update requests from NHGRI

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#562]
Hi Kevin and Dave,

 

I posted some comments in the google doc.

I also have few more comments for the other pages (I could not get to the google doc for them).

 

https://anvilproject.org/ncpi/platforms - please be consistent with the use of acronyms in the light blue box at the top.

 

https://anvilproject.org/ncpi/interoperating-principles - I would highlight the definition of a trust relationship in bold or at least I would make it more prominent.

 

https://anvilproject.org/ncpi/working-groups - please fix my last name: it is Di Francesco (not di Francesco). Stanley’d and Bob’s institutions are missing. Anton’s last name is Nekrutenko (there is a missing final o). in addition to the institution affiliation, there should be the specific NCPI platform the co-chairs represent. The whole page could use some indentation to understand what text belongs to what section, in particular for the sections that have multiple subsections.

 

https://anvilproject.org/ncpi/training/2020-03-17-train-your-colleague

Maybe add the slides to, in addition to the video?

 

https://anvilproject.org/ncpi/progress-updates - maybe announce the next meeting Oct-Nov 2020?

 

Overall: it looks great and I’d like to thank you for the effort.

Best,

Valentina

**Comment by NoopDog** [comment]
* Platforms page - used acronyms for all bit NIH Common Fund
* Interoperating-principles - added section for definition of trust relationship.
* Fixed Di Francesco, Nekrutenko spelling
* Added platform for co-chairs on working group pages.

* Created a separate ticket #565 for slides to 3/17 meeting
* Created ticket #564 to announce upcoming progress meeting
* Created ticket #567 for page layout to make different working groups stand out. Temporarily adjusted outline levels to help.
