### ISSUE TITLE
Include icon/link to AnVIL Project Youtube channel

### ISSUE THREAD

**Issue by MoHeydarian** [anvilproject/anvil-portal#574]
Include icon/link to AnVIL Project Youtube channel along with Twitter, Slack, Github icons at the bottom of the pages.

AnVIL Project Youtube channel: https://www.youtube.com/channel/UCBbHCj7kUogAMFyBAzzzfUw

**Comment by MillenniumFalconMechanic** [comment]
Dupe of #520.
