### ISSUE TITLE
Updating "transfering data to AnVIL" page and proposal to revise \

### ISSUE THREAD

**Issue by MoHeydarian** [anvilproject/anvil-portal#591]

**Comment by NoopDog** [comment]
Superseded by #592

**Comment by candace11** [comment]
@MoHeydarian - where is the transferring data to AnVIL page?  I see under Submitting Consortium data a section called Data Transfer.

**Comment by MoHeydarian** [comment]
Hi @candace11, 
We removed the "transferring data to AnVIL" page, lets talk on [#592](https://github.com/anvilproject/anvil-portal/issues/592) about documenting our complete data ingestion process, reviewing it across the team, and posting to the Portal under the "Data" section.
