### ISSUE TITLE
Updating "transferring data to AnVIL" page and proposal to revise "submitting consortium data" page

### ISSUE THREAD

**Issue by MoHeydarian** [anvilproject/anvil-portal#592]
The "transferring data to AnVIL" page attempted to represent the AnVIL data ingestion process, but only represented our internal team process for making data "live" in Gen3.

The "submitting consortium data" page could be revised to be more specific and reflect our current process now that Gen3 is online. The current page looks like a version of the "ingestion SOP" document, which has been WIP. 

I believe the goal of the two pages mentioned above is to describe the data ingestion process of AnVIL and provide guidance on how the data should be prepared/organized with regard to meta/phenotypic data. 

I propose to create two new pages:
1) Transferring data to AnVIL (describing the end to end process)

2) Requirements for data ingestion (describing the minimal information required for ingestion)

The content for these two pages already largely exists under the "submitting consortium data" page, so this would require some reshuffling, updating, and revision of the current content. 

We can discuss in more depth on the AnVIL PM call next week since a few key people aren't on GH.

**Comment by kozbo** [comment]
Close with submitting data section

**Comment by MillenniumFalconMechanic** [comment]
Closing, obsolete.
