### ISSUE TITLE
Improve display of youtube videos

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#638]
Youtube embeds seem to have a shadow over the top as in:

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/e443b22c-2ecb-4c8d-93ab-5c5578f7cdc4)

May need to have videos redone to remove text in top header.

**Comment by NoopDog** [comment]
This is the default youtube behavior. Need to research further how to make this look better.

**Comment by MillenniumFalconMechanic** [comment]
Displaying as YouTube default.
