### ISSUE TITLE
Create a getting started "Tour" to view full workspace

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#663]
The "Add a billing account" step in getting started can take weeks or longer depending on organizational purchasing constraints etc. To help show what the system is about and to motivate the work required to create a billing account lets consider adding a walk through of a workspace that shows key features but does not incur any cost to view.

One candidate is:

https://anvil.terra.bio/#workspaces/pathogen-genomic-surveillance/COVID-19

Or maybe we should roll our own workspace that has AnVIL data.

**Comment by kozbo** [comment]
@kozbo Can we have Beth help with this
