### ISSUE TITLE
Add FHIR WG's FHIR 101 Guide to NCPI Site

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#672]
https://github.com/ncpi-fhir/fhir-101

**Comment by kozbo** [comment]
Request sent to Robert Carol:

Likely the first step is to create a document that lists the resources you want to include in the site. (Google docs are fine).

We can review your document set and work to figure out how to include these in the NCPI site/sitemap.

Some initial steps we could take are:
Add a high level description of the FHIR work/commitment to the interface to the home page. 
Add a FHIR Resources section to the upcoming "Learn" section listing your resources.
Update the FHIR WG description. 
Add a section on modeling and metadata harmonization approaches etc. if any are envisioned. 

- awaiting Robert's response, expected in the next 2 weeks

**Comment by NoopDog** [comment]
Obsolete
