### ISSUE TITLE
Get an up-to-date list of planned consortia.

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#717]
Consortia name
Website 
Description
Rational

**Comment by kozbo** [comment]
T2T Consortium: https://sites.google.com/ucsc.edu/t2tworkinggroup

**Comment by kozbo** [comment]
See #1100 and this spreadsheet for the latest list
https://docs.google.com/spreadsheets/d/1tNPrdUarVkdryPPgYLQEGRjua5OU6RnAZbzOEQR6t68/edit#gid=1165381953

**Comment by NoopDog** [comment]
Replaced by #1213
