### ISSUE TITLE
Remove titles from Terra Zendesk links

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#728]
From Allie in another channel: For anyone who is linking to Terra documentation (on Zendesk): Links should only include the url up to the random number string. Don’t include the title!!
i.e. use https://support.terra.bio/hc/en-us/articles/360046295092, not https://support.terra.bio/hc/en-us/articles/360046295092-Set-up-billing-with-300-Google-credits-to-explore-Terra.

**Comment by MillenniumFalconMechanic** [comment]
Not needed.
