### ISSUE TITLE
Google Analytics V4 implementation

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#746]
## Need

We currently use Google Analytics V3. This is being sunset next year.  We need to migrate to Google Analytics V4.

## Approach 
1. Familiarize with Google Analytics.
 https://analytics.google.com/analytics/academy/course/6
 https://developers.google.com/analytics
 
1. Familiarize with the AnVIL Google Analytics implementation
https://analytics.google.com/analytics/web/#/croverview/cr-overview/a154456484w227847374p215063242/ (staging)
https://analytics.google.com/analytics/web/#/report-home/a154456484w217975084p207946923 (prod)

1. Familiarize with Google Tag Manager and how this is used in the analytics setup.
https://support.google.com/tagmanager/answer/6102821?hl=en
(let me know if you need access to the anvil account at https://tagmanager.google.com/

1. Prepare a write-up describing the AnVIL Google analytics implementation and any customizations.

1. Explore the google analytics v4 upgrade guide and other material
https://support.google.com/analytics/answer/10759417?hl=en

1. Create a migration plan listing the steps and how to take them, covering changes to the account, the application, tag manager, any custom events, etc. 

1. Review the plan with Mim and me.

1.  Test the plan on the staging analytics account and application, demonstrating it works.

1.  Apply the plan on the prod analytics account and application, demonstrating it works!

- [ ] Create Google Analytics V4 migration plan

**Comment by MillenniumFalconMechanic** [comment]
Superseded by https://github.com/clevercanary/anvil-portal/issues/2.
