### ISSUE TITLE
Add additional help links to AnVIL and re-org

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#838]
The team has been thinking up the best method for guiding users to request help from anvilproject.org/help. We now have discourse, the help listserv and the community slack. We also have links to the support sites of the other platforms. From the user’s perspective, what questions should be asked where?

After a bit of brainstorming, it seems like one method could look something like the table below. We can continue the discussion on Friday during the portal meeting or by email/slack attack. In any case, I wanted to share this thought process and get your feedback.

Similar to:

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/dc793e1e-9832-4a14-8812-f253ac25a6d8)

**Comment by kozbo** [comment]
combine tables and simplify view between two structures

**Comment by kozbo** [comment]
Please hold off on the AnVIL discourse link for approx a month (see mail from Stephen Mosher)
