### ISSUE TITLE
Add Getting Started with Dockstore

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#841]
Being worked on by Ash

**Comment by kozbo** [comment]
Work is complete
https://youtu.be/WLpnoXySuIw
Text to be provided by Ash

**Comment by aofarrel** [comment]
Text is here --> https://gist.github.com/aofarrel/07b0f4da10f2a865f4e18031df57ca5f
Raw markdown --> https://gist.githubusercontent.com/aofarrel/07b0f4da10f2a865f4e18031df57ca5f/raw/adb3ba33d6e4dcb30d481bd66a02de26630c7746/dockstore%2520on%2520anvil.md 

Feel free to comment there (or here) with any suggested edits.
