### ISSUE TITLE
Review conflicting order warnings during gatsby build

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [anvilproject/anvil-portal#878]
We are seeing the following warnings during build:

![Screen Shot 2021-02-25 at 3.04.17 PM.png](https://images.zenhubusercontent.com/57339587bf93871ccd9ae22c/fed51710-a71b-4a95-826d-0fc7597bfcf6)

To do: determine the root cause of the warnings and fix, or add the related `ignore` config flag.

**Comment by NoopDog** [comment]
Obsolete
