### ISSUE TITLE
NCPI dashboard - allow handling of sub studies

### ISSUE THREAD

**Issue by frano-m** [anvilproject/anvil-portal#922]
On the NCPI dashboard, allow handling of any study that is a sub study e.g. https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs000227.v5.p3 is a sub study of https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs000200.v12.p3.

![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/61f994f8-fb41-42d2-b232-bf11967a3063)

**Comment by frano-m** [comment]
#953 #951 #952 #940 resolve handling of sub studies (NCPI dashboard sourced from FHIR).

**Comment by NoopDog** [comment]
FHIR returns data for these. Closing.
